### ISSUE TITLE
what is the zkSync block explorer version?

### ISSUE THREAD

**Issue by q474818917** [matter-labs/hardhat-zksync#1024]
Error in plugin @matterlabs/hardhat-zksync-verify: Solidity compiler you used to compile the contract is not currently supported by zkSync block explorer!
Please use one of the supporting versions

ZkSyncVerifyPluginError: Solidity compiler you used to compile the contract is not currently supported by zkSync block explorer!
Please use one of the supporting versions
    at OverriddenTaskDefinition.verifyContract [as _action] (/Users/wangzx/Downloads/hello-zksync/node_modules/@matterlabs/hardhat-zksync-verify/src/task-actions.ts:200:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Environment._runTaskDefinition (/Users/wangzx/Downloads/hello-zksync/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async hardhatZkSyncVerify (/Users/wangzx/Downloads/hello-zksync/node_modules/@matterlabs/hardhat-zksync-upgradable/src/verify/verify-proxy.ts:42:16)
    at async OverriddenTaskDefinition._action (/Users/wangzx/Downloads/hello-zksync/node_modules/@matterlabs/hardhat-zksync-upgradable/src/index.ts:135:12)
    at async Environment._runTaskDefinition (/Users/wangzx/Downloads/hello-zksync/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Object.Environment.run (/Users/wangzx/Downloads/hello-zksync/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at async verifyContract (/Users/wangzx/Downloads/hello-zksync/deploy/utils.ts:52:41)
    at async deployContract (/Users/wangzx/Downloads/hello-zksync/deploy/utils.ts:112:5)
    at async default_1 (/Users/wangzx/Downloads/hello-zksync/deploy/deploy.ts:9:3)
error Command failed with exit code 1.

**Comment by nikola-bozin-txfusion** [comment]
Hello @q474818917 , here is the link for the supported versions: https://explorer.sepolia.era.zksync.dev/contract_verification/solc_versions.
