### ISSUE TITLE
Error by starting our API with @matterlabs/hardhat-zksync-deploy functionality

### ISSUE THREAD

**Issue by blenkersA** [matter-labs/hardhat-zksync#123]
Hello Girls and Guys,

we have faced a problem by starting our API written in Typescript. If we use in our services for example the Deployer object from your provided package "@matterlabs/hardhat-zksync-deploy" our API can not be started at all (its a little bit more here, explained later). If you comment out the usage of the deployer (see in our example the problematic line of code and just this line of code) everything works fine. If you uncomment it our API will not start.

Our example Service
```
import { Deployer } from "@matterlabs/hardhat-zksync-deploy";
import { Contract, Provider, Wallet } from "zksync-web3";
import * as hre from "hardhat";

export class ContractSmartService {
  constructor(
  ) { }

  public async deployContract(walletKey: string, artifactName: string, deploymentConstructor: Object[]): Promise<string> {
    const wallet = new Wallet(walletKey);

    const deployer = new Deployer(hre, wallet); // Problematic line of code
    /*const artifact = await deployer.loadArtifact(artifactName);

    const contract = await deployer.deploy(artifact, deploymentConstructor);

    return contract.address;*/
    return 'deploy function not implemented';
  }
}
```

Hardhat Config
```
require("@matterlabs/hardhat-zksync-deploy");
require("@matterlabs/hardhat-zksync-solc");

module.exports = {
  zksolc: {
    version: "1.1.5",
    compilerSource: "docker",
    settings: {
      optimizer: {
        enabled: true,
      },
      experimental: {
        dockerImage: "matterlabs/zksolc",
        tag: "v1.1.5"
      },
    },
  },
  zkSyncDeploy: {
    zkSyncNetwork: "https://zksync2-testnet.zksync.dev",
    ethNetwork: "goerli",
  },
  networks: {
    hardhat: {
      zksync: true,
    },
  },
  solidity: {
    version: "0.8.16",
  },
};
```

Error Code
```
HardhatError: HH5: HardhatContext is not created.
    at HardhatContext.getHardhatContext (/home/auel/Projekte/daura/api/node_modules/hardhat/internal/context.js:35:19)
    at extendConfig (/home/auel/Projekte/daura/api/node_modules/hardhat/internal/core/config/config-env.js:66:42)
    at Object.<anonymous> (/home/auel/Projekte/daura/api/node_modules/@matterlabs/hardhat-zksync-deploy/dist/index.js:22:27)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/auel/Projekte/daura/api/dist/src/services/smartContracts/contract.service.js:4:33)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/auel/Projekte/daura/api/dist/src/services/smartContracts/cmtat.service.js:17:28)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19) {
  parent: undefined,
  _stack: 'HardhatError: HH5: HardhatContext is not created.\n' +
    '    at HardhatContext.getHardhatContext (/home/auel/Projekte/daura/api/node_modules/hardhat/internal/context.js:35:19)\n' +
    '    at extendConfig (/home/auel/Projekte/daura/api/node_modules/hardhat/internal/core/config/config-env.js:66:42)\n' +
    '    at Object.<anonymous> (/home/auel/Projekte/daura/api/node_modules/@matterlabs/hardhat-zksync-deploy/dist/index.js:22:27)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1112:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:988:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:834:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1012:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
    '    at Object.<anonymous> (/home/auel/Projekte/daura/api/dist/src/services/smartContracts/contract.service.js:4:33)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1112:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:988:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:834:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1012:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
    '    at Object.<anonymous> (/home/auel/Projekte/daura/api/dist/src/services/smartContracts/cmtat.service.js:17:28)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1112:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:988:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:834:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1012:19)',
  errorDescriptor: {
    number: 5,
    message: 'HardhatContext is not created.',
    title: "Hardhat wasn't initialized",
    description: 'Hardhat initialization failed. This is a bug.\n' +
      '\n' +
      'Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.',
    shouldBeReported: true
  },
  number: 5,
  messageArguments: {},
  _isHardhatError: true
}

Node.js v18.4.0
```

Some for you interesting dependencies we are using
```
"@matterlabs/hardhat-zksync-deploy": "^0.4.0",
"@matterlabs/hardhat-zksync-solc": "^0.3.9",
"@matterlabs/zksync-contracts": "^0.3.3",
"hardhat": "^2.11.2",
"zksync-web3": "^0.9.0",
"ts-node": "^10.9.1",
```

From the stacktrace we found out that there is a problem by using the HardhatContext. This will be extended in your package with the needed network adresses etc. and at this moment you want to extend the context from Hardhat you get the error that Hardhat isn´t created at this point. We testet a little bit around. In our other services we could identify that the context from hardhat is created and we could use it for example to make some log outs by starting this services etc. so we would think that this isn´t a problem at all with hardhat but maybe you have more hints as we have (or we are wrong and should interact with the hardhat team?)

Another intersting fact is, that we have another Service which looks like the same as the one obove and our API started with it. We tested so something around and its something like a coin toss that our API will start. It doesn´t matter if you use one of this services or two or having just one place to interact with the deployer etc.

Service which makes no Problem(?)
```
import { utils, Wallet } from "zksync-web3";
import * as hre from "hardhat";
import { Deployer } from "@matterlabs/hardhat-zksync-deploy";

import { Contract, Web3Provider, Provider } from "zksync-web3";

const GREETER_CONTRACT_ABI = hre.artifacts.readArtifactSync('Greeter').abi;

export class ContractService {
  // Create Contracts
  async createAndDeployContract(greeting: string, walletKey: string): Promise<string> {
    console.log(`WalletKey: ${walletKey}`);
    // Initialize the wallet.
    const wallet = new Wallet(walletKey);

    // Create deployer object
    const deployer = new Deployer(hre, wallet);
    const artifact = await deployer.loadArtifact("Greeter");

    // Deploy this contract
    const greeterContract = await deployer.deploy(artifact, [greeting]);

    // Show the contract info.
    const contractAddress = greeterContract.address;
    console.log(`${artifact.contractName} was deployed to ${contractAddress}`);

    return contractAddress;
  }
}
```

 What we have tested out so far:
* Deleting, comment out etc. something from the services to see when we get to the Problem -> using the Deployer
* Importing Hardhat or using require("hardhat) to interact with the HardhatContext -> at one point require was helping but overall we get the same problem at one point out of nowere
* Using older versions from the dependencies -> didn´t work so far
* See if it is loopback which initialize the services etc. -> Same error if we did´t use loopback to initalize our class
* Playing around with nodejs versions down to 16.x -> not helping

We start our API with the "npm run start" functionality, but would have the same problem if we build and deploy our code in a docker. We didn´t have any problem if we used a script via hardhat to deploy our smart contracts.

Would be nice if you have an Idea whats going wrong :)

**Comment by ly0va** [comment]
Hi @blenkersA thanks for reporting!

When you `import * as hre from 'hardhat'`, the `HardhatContext` will only be initialized as long as the current working directory contains a `hardhat.config.js (ts)`. When running using `npx`, the current working directory is usually the first parent directory that contains a `package.json`.

If this doesn't help, please share a link to the minimal reproducible example so that we can investigate further.

**Comment by blenkersA** [comment]
Hey and thanks for your comment @ly0va 
To make a minimal example with this issue is difficult, it seems not to be clear when this problem occurs.
Interestingly it worked now and we changed nothing. It seems like we have a ghost in the machine which likes now our implementation...

So, I would say solved from my side because it worked but if it will appear again I would try to see if i can gat a reproducible example amd come back.

So thanks and lets hope it will work now :)
