### ISSUE TITLE
Error in plugin @matterlabs/hardhat-zksync-solc: Docker Desktop is not running.

### ISSUE THREAD

**Issue by spsina** [matter-labs/hardhat-zksync#135]
When I want to compile contracts, I keep getting Docker Desktop is not running, even though it's running. I don't know how to diagnose this further.

OS: Pop!_OS 22.04 LTS
Docker version 20.10.21, build baeda1f
hardhat: "^2.9.6",

stack trace:
```
Error in plugin @matterlabs/hardhat-zksync-solc: Docker Desktop is not running.
Please open it and wait until it finishes booting.

NomicLabsHardhatPluginError: Docker Desktop is not running.
Please open it and wait until it finishes booting.
    at pluginError (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/utils.ts:12:12)
    at handleCommonErrors (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/docker.ts:157:30)
    at async createDocker (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/docker.ts:87:12)
    at async Function.initialize (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/index.ts:50:24)
    at async compile (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/index.ts:23:20)
    at async OverriddenTaskDefinition._action (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/index.ts:132:12)
    at async Environment._runTaskDefinition (/home/spsina/dev/unitap/funds-manager/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/home/spsina/dev/unitap/funds-manager/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/home/spsina/dev/unitap/funds-manager/node_modules/hardhat/src/builtin-tasks/compile.ts:700:18)
    at async Environment._runTaskDefinition (/home/spsina/dev/unitap/funds-manager/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)

    Caused by: Error
        at Function.create (/home/spsina/dev/unitap/funds-manager/node_modules/@nomiclabs/hardhat-docker/src/hardhat-docker.ts:28:13)
        at async handleCommonErrors (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/docker.ts:154:16)
        at async createDocker (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/docker.ts:87:12)
        at async Function.initialize (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/index.ts:50:24)
        at async compile (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/index.ts:23:20)
        at async OverriddenTaskDefinition._action (/home/spsina/dev/unitap/funds-manager/node_modules/@matterlabs/hardhat-zksync-solc/src/index.ts:132:12)
        at async Environment._runTaskDefinition (/home/spsina/dev/unitap/funds-manager/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
        at async Environment.run (/home/spsina/dev/unitap/funds-manager/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
        at async SimpleTaskDefinition.action (/home/spsina/dev/unitap/funds-manager/node_modules/hardhat/src/builtin-tasks/compile.ts:700:18)
        at async Environment._runTaskDefinition (/home/spsina/dev/unitap/funds-manager/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
```

**Comment by ly0va** [comment]
Unfortunately, we can't help you with this one. Try using `"compilerSource": "binary"` in `hardhat.config.ts`. It should automatically download and use the needed compiler binary - this eliminates docker as a dependency.

**Comment by ly0va** [comment]
Feel free to reopen if you have any questions
