### ISSUE TITLE
zksync-solc Error: subprocess stdout parsing: EOF while parsing a value at line 1 column 0 (stderr: )

### ISSUE THREAD

**Issue by jedtravis** [matter-labs/hardhat-zksync#1475]
#### 💥 Plugin name

hardhat-zksync-solc

#### 📝 Description

The zksync compiler is throwing an error when compiling contracts that work with the generic solidity compiler. I'm using both Foundry and Hardhat. Foundry isn't throwing any errors during compilation.

#### 📋 Additional Context

Repository: https://github.com/jedtravis/zksync-compiler-error

```
{
  "name": "zksync-hardhat-template",
  "description": "A template for ZKsync smart contracts development with Hardhat",
  "private": true,
  "author": "Matter Labs",
  "license": "MIT",
  "repository": "https://github.com/matter-labs/zksync-hardhat-template.git",
  "scripts": {
    "deploy": "hardhat deploy-zksync --script deploy.ts",
    "interact": "hardhat deploy-zksync --script interact.ts",
    "compile": "run-s compile:forge compile:hardhat",
    "clean": "hardhat clean",
    "test": "hardhat test --network hardhat",
    "size:hardhat": "yarn run hardhat size-contracts",
    "compile:forge": "forge build",
    "compile:hardhat": "npx hardhat compile"
  },
  "devDependencies": {
    "@matterlabs/hardhat-zksync": "^1.1.0",
    "@matterlabs/zksync-contracts": "^0.6.1",
    "@nomicfoundation/hardhat-foundry": "^1.1.2",
    "@nomicfoundation/hardhat-verify": "^2.0.9",
    "@openzeppelin/contracts": "^5.0.2",
    "@openzeppelin/contracts-upgradeable": "^5.0.2",
    "@types/chai": "^4.3.16",
    "@types/mocha": "^10.0.7",
    "chai": "^4.5.0",
    "dotenv": "^16.4.5",
    "ethers": "^6.13.2",
    "hardhat": "^2.22.7",
    "hardhat-contract-sizer": "^2.10.0",
    "mocha": "^10.7.0",
    "npm-run-all": "^4.1.5",
    "ts-node": "^10.9.2",
    "typescript": "^5.5.4",
    "zksync-ethers": "^6.11.0"
  }
}
```

```
import { HardhatUserConfig } from "hardhat/config";

import "hardhat-contract-sizer";
import "@nomicfoundation/hardhat-foundry";
import "@matterlabs/hardhat-zksync";

const config: HardhatUserConfig = {
  defaultNetwork: "zkSyncSepoliaTestnet",
  networks: {
    zkSyncSepoliaTestnet: {
      url: "https://sepolia.era.zksync.dev",
      ethNetwork: "sepolia",
      zksync: true,
      verifyURL: "https://explorer.sepolia.era.zksync.dev/contract_verification",
    },
    zkSyncMainnet: {
      url: "https://mainnet.era.zksync.io",
      ethNetwork: "mainnet",
      zksync: true,
      verifyURL: "https://zksync2-mainnet-explorer.zksync.io/contract_verification",
    },
    dockerizedNode: {
      url: "http://localhost:3050",
      ethNetwork: "http://localhost:8545",
      zksync: true,
    },
    inMemoryNode: {
      url: "http://127.0.0.1:8011",
      ethNetwork: "localhost", // in-memory node doesn't support eth node; removing this line will cause an error
      zksync: true,
    },
    hardhat: {
      zksync: true,
    },
  },
  zksolc: {
    version: "latest",
    settings: {
      // find all available options in the official documentation
      // https://docs.zksync.io/build/tooling/hardhat/hardhat-zksync-solc#configuration
    },
  },
  solidity: {
    version: "0.8.23"
  },
  contractSizer: {
    alphaSort: true,
    disambiguatePaths: false,
    runOnCompile: false,
    strict: false,
    only: [],
  },
};

export default config;
```

```
//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.0;

error ZeroAddressDetected();
error EOAAddressDetected();
error AssetAlreadySupported();

contract Test {
    struct Asset {
        bool supported;
        uint8 index;
    }
    event AssetSupported(address indexed assetAddr);
    mapping(address => Asset) public assets;
    address[] public supportedAssets;

    function addAsset(address assetAddr) external {
        if (assetAddr == address(0)) revert ZeroAddressDetected();
        uint extSize;
        assembly {
            extSize := extcodesize(assetAddr)
        }
        if (extSize == 0) revert EOAAddressDetected();

        Asset memory asset_ = assets[assetAddr];
        if (asset_.supported) revert AssetAlreadySupported();
        assets[assetAddr] = Asset({
            supported: true,
            index: uint8(supportedAssets.length)
        });
        supportedAssets.push(assetAddr);
        emit AssetSupported(assetAddr);
    }
}
```

#### 📎 Log Output

**zksolc v1.5.4**
```
$ npx hardhat compile --show-stack-traces
Compiling contracts for ZKsync Era with zksolc v1.5.4 and zkvm-solc v0.8.23-1.0.1
Compiling 1 Solidity file
Error: C:\Users\johndoe\AppData\Local\hardhat-nodejs\Cache\compilers-v2\zkvm-solc\zkvm-solc-v0.8.23-1.0.1 subprocess stdout parsing: EOF while parsing a value at line 1 column 0 (stderr: )

Error HH600: Compilation failed

HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\builtin-tasks\compile.ts:499:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Environment._runTaskDefinition (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:351:14)
    at async Environment.run (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:184:14)
    at async SimpleTaskDefinition.action (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\builtin-tasks\compile.ts:1424:63)
    at async Environment._runTaskDefinition (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:351:14)
    at async Environment.run (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:184:14)
    at async SimpleTaskDefinition.action (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\builtin-tasks\compile.ts:1504:7)
    at async Environment._runTaskDefinition (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:351:14)
    at async OverriddenTaskDefinition._action (C:\Users\johndoe\Documents\zksync\node_modules\hardhat-contract-sizer\tasks\compile.js:8:3)
```

**zksolc v1.5.5**
```
$ npx hardhat compile --show-stack-traces
Compiling contracts for ZKsync Era with zksolc v1.5.5 and zkvm-solc v0.8.23-1.0.1
Compiling 49 Solidity files
Error: The `solc` executable not found in ${PATH}: cannot find binary path

Error HH600: Compilation failed

HardhatError: HH600: Compilation failed
    at SimpleTaskDefinition.action (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\builtin-tasks\compile.ts:499:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Environment._runTaskDefinition (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:351:14)
    at async Environment.run (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:184:14)
    at async SimpleTaskDefinition.action (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\builtin-tasks\compile.ts:1424:63)
    at async Environment._runTaskDefinition (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:351:14)
    at async Environment.run (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:184:14)
    at async SimpleTaskDefinition.action (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\builtin-tasks\compile.ts:1504:7)
    at async Environment._runTaskDefinition (C:\Users\johndoe\Documents\zksync\node_modules\hardhat\src\internal\core\runtime-environment.ts:351:14)
    at async OverriddenTaskDefinition._action (C:\Users\johndoe\Documents\zksync\node_modules\hardhat-contract-sizer\tasks\compile.js:8:3)
```

**Comment by nikola-bozin-txfusion** [comment]
Hey @jedtravis, could you provide us with the repository where we can reproduce the behaviour?

**Comment by jedtravis** [comment]
Hey @nikola-bozin-txfusion, here you go.
https://github.com/jedtravis/zksync-compiler-error

**Comment by Szczepoo13** [comment]
I am having the same problem! Any updates?

**Comment by kiriyaga-txfusion** [comment]
Hello @jedtravis ,
The forked era solidity compiler on windows doesn't function properly, resulting in compilation errors. The compiler team has been informed and currently working on a fix.

**Comment by Szczepoo13** [comment]
Hello, @kiriyaga-txfusion. By Windows, do you mean WSL? - If yes, how does the situation look on Linux? Thinking of migrating project there :) Thank you for any insights :)

**Comment by jedtravis** [comment]
Just tried compiling with the latest compiler version, v1.5.5, and there's a new error. Added the full error to the first post.

```
Error: The `solc` executable not found in ${PATH}: cannot find binary path

Error HH600: Compilation failed
```

**Comment by kiriyaga-txfusion** [comment]
> Hello, @kiriyaga-txfusion. By Windows, do you mean WSL? - If yes, how does the situation look on Linux? Thinking of migrating project there :) Thank you for any insights :)

Hello @Szczepoo13 ,
Not WSL, I mean normal Windows installation. Everything works correctly in WSL, the Linux subsystem for Windows, just as it does on native Linux. 

I believe some versions of the forked era solidity compiler were fixed yesterday and now are working, so please give them a try. (all versions of solidity after 0.8.18 works)

> Just tried compiling with the latest compiler version, v1.5.5, and there's a new error. Added the full error to the first post.
> 
> ```
> Error: The `solc` executable not found in ${PATH}: cannot find binary path
> 
> Error HH600: Compilation failed
> ```

Hello @jedtravis ,
The latest zksolc compiler isn't working, and compiler team is working on releasing a patched version. In the meantime, please use an older version.

**Comment by Szczepoo13** [comment]
@kiriyaga-txfusion Great! Thank you for your reply. How does the situation with the compiler look like for older versions of Solidity contracts (0.4.0 to 0.6.0), I am trying to deploy UniswapV2 on the zkSync elastic chain :)

**Comment by kaymomin** [comment]
Hi @Szczepoo13, as mentioned by @kiriyaga-txfusion, the compiler team is working on fixes.  Please use an older version of the zksolc compiler. Closing this issue now. But if you face anymore issues or have any questions, feel free to reach out to us again.
