### ISSUE TITLE
hardhat-zksync-verify is not compatible with zksolc v1.2.3

### ISSUE THREAD

**Issue by olivdb** [matter-labs/hardhat-zksync#187]
Verifying a contract compiled with zksolc v1.2.3 returns the following error:

```
ZkSyncVerifyPluginError: Unknown zksolc version: v1.2.3
    at SimpleTaskDefinition.verifyMinimumBuild [as action] (/xdomain/packages/zksync-dai-bridge/node_modules/@matterlabs/hardhat-zksync-verify/src/task-actions.ts:194:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Environment._runTaskDefinition (/xdomain/packages/zksync-dai-bridge/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/xdomain/packages/zksync-dai-bridge/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async OverriddenTaskDefinition.verifyContract [as _action] (/xdomain/packages/zksync-dai-bridge/node_modules/@matterlabs/hardhat-zksync-verify/src/task-actions.ts:146:5)
    at async Environment._runTaskDefinition (/xdomain/packages/zksync-dai-bridge/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Object.Environment.run (/xdomain/packages/zksync-dai-bridge/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async deployL2Contract (/xdomain/packages/zksync-dai-bridge/zksync-helpers/deploy.ts:25:7)
    at async Context.<anonymous> (/xdomain/packages/zksync-dai-bridge/test-e2e/bridge.test.ts:84:25)
```

**Comment by FilipTxFusion** [comment]
zksolc v1.2.3 is supported in the newest verify plugin version we will release soon

**Comment by stevyhacker** [comment]
I get this now when trying to verify a contract compiled with 1.3.2:
ZkSyncVerifyPluginError: Unknown zksolc version: v1.3.2
I assume you will release a new verify plugin soon?

**Comment by FilipTxFusion** [comment]
Yes, the newest verify plugin version will support both zksolc v1.2.3 and v1.3.2 along with additional plugin improvements.
