### ISSUE TITLE
Error in `@matterlabs/hardhat-zksync-vyper`: `contains invalid WIN32 path characters.`

### ISSUE THREAD

**Issue by pcaversaccio** [matter-labs/hardhat-zksync#396]
First, to clarify everything works smoothly on my Ubuntu OS. This issue is _only_ a problem on Windows.

Compiling the following Vyper contract:

```vyper
# @version ^0.3.9

IMMUTABLE_1: public(immutable(String[4]))

@external
def __init__():
    IMMUTABLE_1 = "Test"
```

with the following config file:

```ts
import * as dotenv from "dotenv";

import { HardhatUserConfig } from "hardhat/config";
import "@nomiclabs/hardhat-ethers";
import "@nomiclabs/hardhat-vyper";
import "@nomicfoundation/hardhat-verify";
import "@typechain/hardhat";
import "@matterlabs/hardhat-zksync-solc";
import "@matterlabs/hardhat-zksync-vyper";
import "@matterlabs/hardhat-zksync-deploy";
import "@matterlabs/hardhat-zksync-verify";
import "@matterlabs/hardhat-zksync-verify-vyper";

dotenv.config();

const config: HardhatUserConfig = {
  paths: {
    sources: "./contracts/vyper",
  },
  solidity: {
    version: "0.8.19",
    settings: {
      optimizer: {
        enabled: true,
        runs: 999999,
      },
    },
  },
  vyper: {
    version: "0.3.9",
  },
  zksolc: {
    version: "1.3.14",
    compilerSource: "binary",
    settings: {
      isSystem: false,
      forceEvmla: false,
      optimizer: {
        enabled: true,
        mode: "3",
      },
    },
  },
  zkvyper: {
    version: "1.3.10",
    settings: {
      libraries: {},
    },
  },
  networks: {
    hardhat: {
      chainId: 31337,
      hardfork: "shanghai",
      zksync: true,
    },
    zkSyncLocal: {
      chainId: 270,
      url: "http://localhost:3050",
      ethNetwork: "http://localhost:8545",
      zksync: true,
    },
    goerli: {
      chainId: 5,
      url: process.env.ETH_GOERLI_TESTNET_URL || "",
      accounts:
        process.env.PRIVATE_KEY !== undefined ? [process.env.PRIVATE_KEY] : [],
    },
    sepolia: {
      chainId: 11155111,
      url: process.env.ETH_SEPOLIA_TESTNET_URL || "",
      accounts:
        process.env.PRIVATE_KEY !== undefined ? [process.env.PRIVATE_KEY] : [],
    },
    zkSyncTestnet: {
      chainId: 280,
      url: process.env.ZKSYNC_TESTNET_URL || "",
      ethNetwork: process.env.ETH_GOERLI_TESTNET_URL || "",
      zksync: true,
      verifyURL:
        "https://zksync2-testnet-explorer.zksync.dev/contract_verification",
    },
    zkSyncMain: {
      chainId: 324,
      url: process.env.ZKSYNC_MAINNET_URL || "",
      ethNetwork: process.env.ETH_MAINNET_URL || "",
      zksync: true,
      verifyURL:
        "https://zksync2-mainnet-explorer.zksync.io/contract_verification",
    },
  },
  etherscan: {
    apiKey: {
      // For Ethereum testnets
      goerli: process.env.ETHERSCAN_API_KEY || "",
      sepolia: process.env.ETHERSCAN_API_KEY || "",
    },
  },
};

export default config;
```

will throw with:

```
Compiling contracts for zkSync Era with zkvyper v1.3.10 and vyper v0.3.9
An unexpected error occurred:

Error: C:\Dev\Blockchain\zksync-vyper-sandbox\artifacts-zk\?\C:\Dev\Blockchain\zksync-vyper-sandbox\contracts\vyper\Foo.vy contains invalid WIN32 path characters.
    at Object.mkdirs (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)
    at C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\fs-extra\node_modules\universalify\index.js:13:12
    at new Promise (<anonymous>)
    at Object.mkdirs (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\fs-extra\node_modules\universalify\index.js:7:14)
    at ZkArtifacts.saveArtifactAndDebugFile (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\hardhat\src\internal\artifacts.ts:230:21)
    at ZkArtifacts.saveArtifactAndDebugFile (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\@matterlabs\hardhat-zksync-vyper\src\artifacts.ts:42:32)
    at SimpleTaskDefinition.action (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\@nomiclabs\hardhat-vyper\src\index.ts:320:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Environment._runTaskDefinition (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\hardhat\src\internal\core\runtime-environment.ts:333:14)
    at async Environment.run (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\hardhat\src\internal\core\runtime-environment.ts:166:14) {
  code: 'EINVAL'
```

You should be considering making the path resolution OS agnostic. Again, on Linux everything is fine. Also, compiling it only with `@nomiclabs/hardhat-vyper` works smoothly.

**Comment by kiriyaga-txfusion** [comment]
Thank you for reporting this issue, it appears that there is a problem compiling the contracts on Windows. We added this task to our backlog and we will get to work on it as soon as other priorities are solved.

**Comment by pcaversaccio** [comment]
As an update, the latest `hardhat-zksync-vyper` fixes this issue BUT `hardhat-zksync-verify-vyper` still has that issue.

**Comment by pcaversaccio** [comment]
> Do you use zkvyper when compiling or just vyper? I'm still having this problem and I don't think it's fixed on the compiler side or on the plugin side. I recommend that you use WSL on Windows, which is hardhat's recommendation itself. We added this task to our backlog and we will get to work on it as soon as other priorities are solved.

zkvyper, but maybe I used WSL for that run. You can test my setup here: https://github.com/pcaversaccio/zksync-vyper-sandbox

**Comment by kiriyaga-txfusion** [comment]
Hello @pcaversaccio, fix is merged and it will be released with next version of plugin.
