### ISSUE TITLE
ERC721 Compile error

### ISSUE THREAD

**Issue by skar395** [matter-labs/hardhat-zksync#49]
Hello everybody,
i was following the tutorial to compile an ERC721, i get this error:

```
Compiling 14 files with 0.8.10
Error in plugin @matterlabs/hardhat-zksync-solc: thread 'main' panicked at 'Always valid: Error("missing field `irOptimized`", line: 1, column: 719)', src/solc/mod.rs:86:76
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


NomicLabsHardhatPluginError: thread 'main' panicked at 'Always valid: Error("missing field `irOptimized`", line: 1, column: 719)', src/solc/mod.rs:86:76
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    at pluginError (/home/pietro/Documenti/Projects/zkloot-example/node_modules/@matterlabs/hardhat-zksync-solc/src/utils.ts:10:12)
    at runZksolcContainer (/home/pietro/Documenti/Projects/zkloot-example/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/docker.ts:68:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at handleCommonErrors (/home/pietro/Documenti/Projects/zkloot-example/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/docker.ts:143:16)
    at compileWithDocker (/home/pietro/Documenti/Projects/zkloot-example/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/docker.ts:138:12)
    at DockerCompiler.compile (/home/pietro/Documenti/Projects/zkloot-example/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/index.ts:61:16)
    at compile (/home/pietro/Documenti/Projects/zkloot-example/node_modules/@matterlabs/hardhat-zksync-solc/src/compile/index.ts:24:12)
    at OverriddenTaskDefinition._action (/home/pietro/Documenti/Projects/zkloot-example/node_modules/@matterlabs/hardhat-zksync-solc/src/index.ts:82:12)
    at Environment._runTaskDefinition (/home/pietro/Documenti/Projects/zkloot-example/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/pietro/Documenti/Projects/zkloot-example/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
error Command failed with exit code 1.
```

I'm using there imports:
```
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
```

Am I using features that are not yet supported?

**Comment by lsbyerley** [comment]
I am running into the same issue with ERC721URIStorage from open zeppelin..

```
import "@openzeppelin/contracts/utils/Counters.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
```

**Comment by ly0va** [comment]
We're looking into it, will get back to you as soon as we have a solution.

**Comment by ly0va** [comment]
Docker image was updated. Make sure you are using the latest [matterlabs/zksolc](https://hub.docker.com/r/matterlabs/zksolc)
 @lsbyerley @skar395 Please try again and let us know if you have any issues.

**Comment by lsbyerley** [comment]
@ly0va thank's it is working for me now! If i could only find some goerli ETH so I can pay for the deploy :)

**Comment by ly0va** [comment]
Great. Feel free to request test ETH on [this channel](https://discord.com/channels/722409280497516566/946465891825102868) on our discord!

**Comment by lsbyerley** [comment]
> Great. Feel free to request test ETH on [this channel](https://discord.com/channels/722409280497516566/946465891825102868) on our discord!

Yep.. i did! (lukeb#4199)

**Comment by skar395** [comment]
Thank you, it's working also for me now :)
