### ISSUE TITLE
`Class extends value undefined is not a constructor or null` error with Ethers 6 plugins

### ISSUE THREAD

**Issue by idea404** [matter-labs/hardhat-zksync#547]
#### 💥 Plugin name

```json
  "dependencies": {
    "@matterlabs/hardhat-zksync-deploy": "^1.0.1",
    "@matterlabs/hardhat-zksync-solc": "^1.0.3",
    "@matterlabs/hardhat-zksync-verify": "^1.1.1",
    "hardhat": "^2.19.2",
    "ts-node": "^10.9.1",
    "typescript": "^5.3.3"
  }
```

#### 📝 Description

This error appears when I attempt to run `yarn hardhat compile` with the Ethers 6 plugin versions above. 

#### 🔄 Reproduction Steps

```sh
git clone https://github.com/idea404/simple && cd simple && yarn && yarn hardhat compile
```

#### 🤔 Expected Behavior

For contract to compile.

#### 😯 Current Behavior

```sh
yarn hardhat compile
yarn run v1.22.19
$ /Users/dennis/Documents/Code/simple/node_modules/.bin/hardhat compile
An unexpected error occurred:

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/dennis/Documents/Code/simple/node_modules/zksync2-js/build/src/types.js:46:51)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/Users/dennis/Documents/Code/simple/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/dennis/Documents/Code/simple/node_modules/zksync2-js/build/src/utils.js:19:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nikola-bozin-txfusion** [comment]
Hey @idea404, you are missing "ethers": "version" as a dependency in your package.json. Please add it like this: "ethers":"^6.7.1".
