### ISSUE TITLE
Bug: `TypeError: deployedBytecode.getExecutableSection is not a function`

### ISSUE THREAD

**Issue by pcaversaccio** [matter-labs/hardhat-zksync#572]
Repository for repro: https://github.com/pcaversaccio/batch-distributor

## Summary

When I normally deploy via e.g. `pnpm deploy:goerli`, I will get the following error triggered by my programmatic verification script (see [here](https://github.com/pcaversaccio/batch-distributor/blob/main/scripts/deploy.ts#L18)):

```
BatchDistributor deployed to: 0x0f2e80d541f4AF41B9c140E13Bb735DD5627A034
TypeError: deployedBytecode.getExecutableSection is not a function
    at compareBytecode (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\@matterlabs+hardhat-zksync-verify@1.2.0_@nomicfoundation+hardhat-verify@2.0.2_ethers@6.9.0_hardhat@2.19.2\node_modules\@matterlabs\hardhat-zksync-verify\src\solc\bytecode.ts:86:56)
    at extractMatchingContractInformation (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\@matterlabs+hardhat-zksync-verify@1.2.0_@nomicfoundation+hardhat-verify@2.0.2_ethers@6.9.0_hardhat@2.19.2\node_modules\@matterlabs\hardhat-zksync-verify\src\solc\bytecode.ts:61:21)
    at inferContractArtifacts (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\@matterlabs+hardhat-zksync-verify@1.2.0_@nomicfoundation+hardhat-verify@2.0.2_ethers@6.9.0_hardhat@2.19.2\node_modules\@matterlabs\hardhat-zksync-verify\src\plugin.ts:37:77)
    at async OverriddenTaskDefinition.getContractInfo [as _action] (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\@matterlabs+hardhat-zksync-verify@1.2.0_@nomicfoundation+hardhat-verify@2.0.2_ethers@6.9.0_hardhat@2.19.2\node_modules\@matterlabs\hardhat-zksync-verify\src\task-actions.ts:247:31)
    at async Environment._runTaskDefinition (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\hardhat@2.19.2_ts-node@10.9.2_typescript@5.3.3\node_modules\hardhat\src\internal\core\runtime-environment.ts:358:14)
    at async Environment.run (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\hardhat@2.19.2_ts-node@10.9.2_typescript@5.3.3\node_modules\hardhat\src\internal\core\runtime-environment.ts:191:14)
    at async SimpleTaskDefinition.action (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\@nomicfoundation+hardhat-verify@2.0.2_hardhat@2.19.2\node_modules\@nomicfoundation\hardhat-verify\src\internal\tasks\etherscan.ts:130:62)
    at async Environment._runTaskDefinition (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\hardhat@2.19.2_ts-node@10.9.2_typescript@5.3.3\node_modules\hardhat\src\internal\core\runtime-environment.ts:358:14)
    at async Environment.run (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\hardhat@2.19.2_ts-node@10.9.2_typescript@5.3.3\node_modules\hardhat\src\internal\core\runtime-environment.ts:191:14)
    at async SimpleTaskDefinition.action (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\@nomicfoundation+hardhat-verify@2.0.2_hardhat@2.19.2\node_modules\@nomicfoundation\hardhat-verify\src\index.ts:285:7)
    at async Environment._runTaskDefinition (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\hardhat@2.19.2_ts-node@10.9.2_typescript@5.3.3\node_modules\hardhat\src\internal\core\runtime-environment.ts:358:14)
    at async OverriddenTaskDefinition.verifyContract [as _action] (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\@matterlabs+hardhat-zksync-verify@1.2.0_@nomicfoundation+hardhat-verify@2.0.2_ethers@6.9.0_hardhat@2.19.2\node_modules\@matterlabs\hardhat-zksync-verify\src\task-actions.ts:130:16)
    at async Environment._runTaskDefinition (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\hardhat@2.19.2_ts-node@10.9.2_typescript@5.3.3\node_modules\hardhat\src\internal\core\runtime-environment.ts:358:14)
    at async Environment.run (C:\Dev\Blockchain\batch-distributor\node_modules\.pnpm\hardhat@2.19.2_ts-node@10.9.2_typescript@5.3.3\node_modules\hardhat\src\internal\core\runtime-environment.ts:191:14)
    at async main (C:\Dev\Blockchain\batch-distributor\scripts\deploy.ts:18:3)
 ELIFECYCLE  Command failed with exit code 1.
```

It looks like somehow that `hardhat-zksync-verify` interferes with my normal verification script. I use the latest dependencies and the zk-sync deployment script can be found [here](https://github.com/pcaversaccio/batch-distributor/blob/main/deploy/deploy-zksync.ts).

**Comment by nikola-bozin-txfusion** [comment]
Hello, please bump your `hardhat-zksync-verify` plugin to latest `1.2.1` version, this should fix the issue.

**Comment by pcaversaccio** [comment]
> Hello, please bump your `hardhat-zksync-verify` plugin to latest `1.2.1` version, this should fix the issue.

Confirmed, it's fixed.
