### ISSUE TITLE
Windows Compilation Error: `@matterlabs/hardhat-zksync-vyper`

### ISSUE THREAD

**Issue by pcaversaccio** [matter-labs/hardhat-zksync#626]
I think this [PR](https://github.com/matter-labs/hardhat-zksync/pull/479) introduced a bug. Let's use my sandbox environment to reproduce the bug: https://github.com/pcaversaccio/zksync-vyper-sandbox.

### Windows

1. Run `npx hardhat compile --force`
2. Run `pnpm deploy:zksynctestnet`:
```console
An unexpected error occurred:

Error: The bytecode length in bytes must be divisible by 32
    at hashBytecode (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\.pnpm\zksync-ethers@6.0.0_ethers@6.9.1\node_modules\zksync-ethers\build\src\utils.js:187:15)
    at ContractFactory.getDeployTransaction (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\.pnpm\zksync-ethers@6.0.0_ethers@6.9.1\node_modules\zksync-ethers\build\src\contract.js:67:55)    
    at async ContractFactory.deploy (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\.pnpm\ethers@6.9.1\node_modules\ethers\src.ts\contract\factory.ts:105:20)
    at async ContractFactory.deploy (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\.pnpm\zksync-ethers@6.0.0_ethers@6.9.1\node_modules\zksync-ethers\build\src\contract.js:125:26)
    at async Deployer.deploy (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\.pnpm\@matterlabs+hardhat-zksync-deploy@1.1.2_ethers@6.9.1_hardhat@2.19.3_zksync-ethers@6.0.0\node_modules\@matterlabs\hardhat-zksync-deploy\src\deployer.ts:207:26)
    at async main (C:\Dev\Blockchain\zksync-vyper-sandbox\deploy\deploy-zksync.ts:44:20)
    at async runScript (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\.pnpm\@matterlabs+hardhat-zksync-deploy@1.1.2_ethers@6.9.1_hardhat@2.19.3_zksync-ethers@6.0.0\node_modules\@matterlabs\hardhat-zksync-deploy\src\plugin.ts:77:5)
    at async callDeployScripts (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\.pnpm\@matterlabs+hardhat-zksync-deploy@1.1.2_ethers@6.9.1_hardhat@2.19.3_zksync-ethers@6.0.0\node_modules\@matterlabs\hardhat-zksync-deploy\src\plugin.ts:54:17)
    at async SimpleTaskDefinition.zkSyncDeploy [as action] (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\.pnpm\@matterlabs+hardhat-zksync-deploy@1.1.2_ethers@6.9.1_hardhat@2.19.3_zksync-ethers@6.0.0\node_modules\@matterlabs\hardhat-zksync-deploy\src\task-actions.ts:5:5)
    at async Environment._runTaskDefinition (C:\Dev\Blockchain\zksync-vyper-sandbox\node_modules\.pnpm\hardhat@2.19.3_ts-node@10.9.2_typescript@5.3.3\node_modules\hardhat\src\internal\core\runtime-environment.ts:358:14)
 ELIFECYCLE  Command failed with exit code 1.
```

### Linux
1. Run `npx hardhat compile --force`
2. Run `pnpm deploy:zksynctestnet`:
```console
Foo deployed to: 0x...

Waiting 30 seconds before beginning the contract verification to allow the block explorer to index the contract...
```

Furthermore, if I first compile the `Foo` contract with Linux and after deploy via Windows OS:

```console
Foo deployed to: 0x...

Waiting 30 seconds before beginning the contract verification to allow the block explorer to index the contract...

Compiling contracts for zkSync Era with zkvyper v1.3.14 and vyper v0.3.10
Error in plugin @matterlabs/hardhat-zksync-verify-vyper: The address provided as argument contains a contract, but its bytecode doesn't match any of your local contracts.

      Possible causes are:
        - Contract code changed after the deployment was executed. This includes code for seemingly unrelated contracts.
        - A vyper file was added, moved, deleted or renamed after the deployment was executed. This includes files for seemingly unrelated contracts.
        - Vyper compiler settings were modified after the deployment was executed (like the optimizer, target EVM, etc.).
        - The given address is wrong.
        - The selected network is wrong.
```

So the Windows compilation is still not properly implemented and results in incompatible and wrong bytecode...

**Comment by hedgar2017** [comment]
I'm only able to try Windows through `parallels` on Mac, and there things seem to be more complicated:
```
hedgarmac@DD91 CLANGARM64 /z/Desktop/zksync-vyper-sandbox
$ npx hardhat compile --force
WARNING: You are currently using Node.js v21.5.0, which is not supported by Hardhat. This can lead to unexpected behavior. See https://hardhat.org/nodejs-versions


Downloading zksolc 1.3.19
zksolc version 1.3.19 successfully downloaded
No need to generate any newer typings.
Downloading vyper 0.3.10
Downloading zkvyper 1.3.14
zkvyper version 1.3.14 successfully downloaded
Compiling contracts for zkSync Era with zkvyper v1.3.14 and vyper v0.3.10
An unexpected error occurred:

Error: \\Mac\Home\Desktop\zksync-vyper-sandbox\artifacts-zk\?\UNC\Mac\Home\Desktop\zksync-vyper-sandbox\contracts\vyper\Foo.vy contains invalid WIN32 path characters.
    at Object.mkdirs (Z:\Desktop\zksync-vyper-sandbox\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)
    at Z:\Desktop\zksync-vyper-sandbox\node_modules\fs-extra\node_modules\universalify\index.js:13:12
    at new Promise (<anonymous>)
    at Object.mkdirs (Z:\Desktop\zksync-vyper-sandbox\node_modules\fs-extra\node_modules\universalify\index.js:7:14)
    at ZkArtifacts.saveArtifactAndDebugFile (Z:\Desktop\zksync-vyper-sandbox\node_modules\hardhat\src\internal\artifacts.ts:224:21)
    at ZkArtifacts.saveArtifactAndDebugFile (Z:\Desktop\zksync-vyper-sandbox\node_modules\@matterlabs\hardhat-zksync-vyper\src\artifacts.ts:42:32)
    at SimpleTaskDefinition.action (Z:\Desktop\zksync-vyper-sandbox\node_modules\@nomiclabs\hardhat-vyper\src\index.ts:320:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Environment._runTaskDefinition (Z:\Desktop\zksync-vyper-sandbox\node_modules\hardhat\src\internal\core\runtime-environment.ts:358:14)
    at async Environment.run (Z:\Desktop\zksync-vyper-sandbox\node_modules\hardhat\src\internal\core\runtime-environment.ts:191:14) {
  code: 'EINVAL'
}
```
The plugin crashed before it had a chance to compile stuff.

**Comment by pcaversaccio** [comment]
@hedgar2017 did you use the latest version? I reported this bug already here https://github.com/matter-labs/hardhat-zksync/issues/396 and I thought it was fixed...

**Comment by hedgar2017** [comment]
> @hedgar2017 did you use the latest plugin version? I reported this bug already here #396 and I thought it was fixed...

I just followed the commands to reproduce.

**Comment by hedgar2017** [comment]
> @hedgar2017 did you use the latest plugin version? I reported this bug already here #396 and I thought it was fixed...

Could you clarify which dependency I should update, and to which version?

**Comment by mpopovac-txfusion** [comment]
We tried it on the Windows machine as well, and the compile command passed, meaning the compiler returned bytecode in the output (the same as @pcaversaccio). The problem arises when attempting to deploy that bytecode to the network. We compared the bytecode with the one returned on Linux, and it is not the same. 
The [PR](https://github.com/matter-labs/hardhat-zksync/pull/479) that is mentioned relates to fixing the Windows paths returned by the compiler and is not connected to the bytecode returned.

**Comment by hedgar2017** [comment]
> We tried it on the Windows machine as well, and the compile command passed, meaning the compiler returned bytecode in the output (the same as @pcaversaccio). The problem arises when attempting to deploy that bytecode to the network. We compared the bytecode with the one returned on Linux, and it is not the same. The [PR](https://github.com/matter-labs/hardhat-zksync/pull/479) that is mentioned relates to fixing the Windows paths returned by the compiler and is not connected to the bytecode returned.

Could you provide more detail on what's going on with the Windows bytecode? Can we see it?
Is it different from bytecode on Linux or MacOS?
Can it be a problem with the deployment logic?

**Comment by pcaversaccio** [comment]
> > @hedgar2017 did you use the latest plugin version? I reported this bug already here #396 and I thought it was fixed...
> 
> Could you clarify which dependency I should update, and to which version? hardhat-zksync-vyper is 1.0.5, which seems to be the latest.

Interesting - in that case it should actually work... 


## Windows Bytecode

```json
{
  "_format": "hh-zkvyper-artifact-1",
  "contractName": "Foo",
  "sourceName": "contracts/vyper/Foo.vy",
  "abi": [
    {
      "inputs": [],
      "outputs": [],
      "stateMutability": "payable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "IMMUTABLE_1",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x60b35150610008565b60046040527f5465737400000000000000000000000000000000000000000000000000000000602060400152604060208151015f602082601f01046002811161008a57801561007057905b60208102840151602082025f01609301525b600101818118610053575b50505050610079565b61009361008e6000396100d36000f3005b5f80fd600436101561000d5761008a565b5f3560e01c63a21155f08114156100845734151561008f5760043610151561008f57610034565b6020805f6040015280604001602060206100935f395f51018061009383395080518060208301016020825f03063682375050601f19601f825160200101169050810190508090506040610082565bf35b5061008a565b5f5ffd005b5f80fd841893801840a16576797065728300030a0013",
  "deployedBytecode": "0x600436101561000d5761008a565b5f3560e01c63a21155f08114156100845734151561008f5760043610151561008f57610034565b6020805f6040015280604001602060206100935f395f51018061009383395080518060208301016020825f03063682375050601f19601f825160200101169050810190508090506040610082565bf35b5061008a565b5f5ffd005b5f80fd",
  "linkReferences": {},
  "deployedLinkReferences": {},
  "factoryDeps": {}
}
```

## Linux Bytecode

```json
{
  "_format": "hh-zkvyper-artifact-1",
  "contractName": "Foo",
  "sourceName": "contracts/vyper/Foo.vy",
  "abi": [
    {
      "inputs": [],
      "outputs": [],
      "stateMutability": "payable",
      "type": "constructor"
    },
    {
      "inputs": [],
      "name": "IMMUTABLE_1",
      "outputs": [
        {
          "name": "",
          "type": "string"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x000200000000000200050000000000020001000000010355000000000301001900000060033002700000001f0030019d0000001f0330019700000001022001900000005e0000c13d000000030230008c0000006c0000a13d000000000101043b0000002201100197000000230110009c0000006c0000c13d0000000001000416000000000101004b0000006c0000c13d0000002001000039000000400010043f000000240100004100000000001004390000000001000412000300000001001d000000040010044300000024000004430000001f0100004100000000020004140000001f0320009c0000000002018019000000c00120021000000025011001c70000800502000039007500700000040f00000001022001900000006e0000613d000000000101043b000200200010003e000000410000613d0000006002000039000180050000003d0000000003000019000500000002001d0000002401000041000000000010043900000003010000290000000400100443000400000003001d000000240030044300000000010004140000001f0210009c0000001f01008041000000c00110021000000025011001c70000000102000029007500700000040f00000001022001900000006e0000613d000000000101043b0000000502000029000000000212043600000004030000290000002003300039000000020130006c0000002a0000413d000000600100043d00000000021000490000001f02200190000000530000613d0000000003000031000000010330036700000080011000390000000302200210000000000401043300000000042401cf000000000424022f00000100022000890000000003300350000000000303043b000000000323022f00000000022301cf000000000242019f0000000000210435000000600100043d00000000021000490000001f0220018f000000000121001900000040011000390000001f020000410000001f0310009c0000000001028019000000600110021000000026011001c7000000760001042e0000000401000039000000400010043f0000002002000041000000600020043f0000014000000443000001600010044300000020010000390000018000100443000001a0002004430000010000100443000000020100003900000120001004430000002101000041000000760001042e00000000010000190000007700010430000000000001042f000000000001042f00000073002104230000000102000039000000000001042d0000000002000019000000000001042d0000007500000432000000760001042e0000007700010430000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff546573740000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000c0000001000000000000000000ffffffff00000000000000000000000000000000000000000000000000000000a21155f000000000000000000000000000000000000000000000000000000000310ab089e4439a4c15d089f94afb7896ff553aecb10793d0ab882de59d99a32e0200000200000000000000000000000000000044000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000002081864edf9a176847016c2633e1758444f41065ebe673e72f707325e3930a81",
  "deployedBytecode": "0x000200000000000200050000000000020001000000010355000000000301001900000060033002700000001f0030019d0000001f0330019700000001022001900000005e0000c13d000000030230008c0000006c0000a13d000000000101043b0000002201100197000000230110009c0000006c0000c13d0000000001000416000000000101004b0000006c0000c13d0000002001000039000000400010043f000000240100004100000000001004390000000001000412000300000001001d000000040010044300000024000004430000001f0100004100000000020004140000001f0320009c0000000002018019000000c00120021000000025011001c70000800502000039007500700000040f00000001022001900000006e0000613d000000000101043b000200200010003e000000410000613d0000006002000039000180050000003d0000000003000019000500000002001d0000002401000041000000000010043900000003010000290000000400100443000400000003001d000000240030044300000000010004140000001f0210009c0000001f01008041000000c00110021000000025011001c70000000102000029007500700000040f00000001022001900000006e0000613d000000000101043b0000000502000029000000000212043600000004030000290000002003300039000000020130006c0000002a0000413d000000600100043d00000000021000490000001f02200190000000530000613d0000000003000031000000010330036700000080011000390000000302200210000000000401043300000000042401cf000000000424022f00000100022000890000000003300350000000000303043b000000000323022f00000000022301cf000000000242019f0000000000210435000000600100043d00000000021000490000001f0220018f000000000121001900000040011000390000001f020000410000001f0310009c0000000001028019000000600110021000000026011001c7000000760001042e0000000401000039000000400010043f0000002002000041000000600020043f0000014000000443000001600010044300000020010000390000018000100443000001a0002004430000010000100443000000020100003900000120001004430000002101000041000000760001042e00000000010000190000007700010430000000000001042f000000000001042f00000073002104230000000102000039000000000001042d0000000002000019000000000001042d0000007500000432000000760001042e0000007700010430000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff546573740000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000c0000001000000000000000000ffffffff00000000000000000000000000000000000000000000000000000000a21155f000000000000000000000000000000000000000000000000000000000310ab089e4439a4c15d089f94afb7896ff553aecb10793d0ab882de59d99a32e0200000200000000000000000000000000000044000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000002081864edf9a176847016c2633e1758444f41065ebe673e72f707325e3930a81",
  "linkReferences": {},
  "deployedLinkReferences": {},
  "factoryDeps": {}
}
```

It looks like that the Windows compilation does not return the zksync-specific bytecode...

**Comment by pcaversaccio** [comment]
I quickly tested with the latest release [`[@matterlabs/hardhat-zksync-vyper-v1.0.6](https://github.com/matter-labs/hardhat-zksync/releases/tag/%40matterlabs%2Fhardhat-zksync-vyper-v1.0.6)`](https://github.com/matter-labs/hardhat-zksync/releases/tag/%40matterlabs%2Fhardhat-zksync-vyper-v1.0.6) it seems to work properly now. Closing the issue accordingly.
