### ISSUE TITLE
deploy-zksync errors with wrong nonce

### ISSUE THREAD

**Issue by joewagner** [matter-labs/hardhat-zksync#71]
Hi,
I've been using [this tutorial](https://v2-docs.zksync.io/api/hardhat/getting-started.html) to try to deploy my own very simple Smart Contract.  I've got the compile command to work.  When I run the deploy command. It seems to be working, but after a minute or so I get an error saying the Tx nonce is incorrect.
In the error output you can see the nonce is `0`, which seems wrong.  Am I missing something in how the nonce is chosen?
Thanks for any help or guidance!

Here's the full error:

```
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":3,\"message\":\"Execution error\",\"data\":{\"code\":104,\"message\":\"Tx nonce is incorrect. Another transaction with the nonce 0 is already accepted.\"}},\"id\":685}\n", error={"code":3,"data":{"code":104,"message":"Tx nonce is incorrect. Another transaction with the nonce 0 is already accepted."}}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x70f9537e80826f9c82294094" ... many more characters ],\"id\":685,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://zksync2-testnet.zksync.dev", code=SERVER_ERROR, version=web/5.5.1)
    at Logger.makeError (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at /path/to/repo/node_modules/ethers/node_modules/@ethersproject/web/src.ts/index.ts:321:28
    at step (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/web/lib/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","error":{"code":3,"message":"Execution error","data":{"code":104,"message":"Tx nonce is incorrect. Another transaction with the nonce 0 is already accepted."}},"id":685}\n',
  error: Error: Execution error
      at getResult (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:97:28)
      at processJsonFunc (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/web/src.ts/index.ts:363:22)
      at /path/to/repo/node_modules/ethers/node_modules/@ethersproject/web/src.ts/index.ts:300:42
      at step (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/path/to/repo/node_modules/ethers/node_modules/@ethersproject/web/lib/index.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: 3,
    data: {
      code: 104,
      message: 'Tx nonce is incorrect. Another transaction with the nonce 0 is already accepted.'
    }
  },
  requestBody: '{"method":"eth_sendRawTransaction","params":["0x70f9537e80826f9c8'... many more characters,
  requestMethod: 'POST',
  url: 'https://zksync2-testnet.zksync.dev',
  transaction: {
    type: 112,
    nonce: 0,
    gasPrice: BigNumber { _hex: '0x6f9c', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0x2940', _isBigNumber: true },
    to: '0x0000000000000000000000000000000000000000',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0xbe253f146b07e69aff69fa8c7aa24214e9d5deed65571b271fe4b777969621050000000000000000010000000000000000000000000000000000000000000000',
    chainId: BigNumber { _hex: '0x0118', _isBigNumber: true },
    customData: {
      feeToken: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
      withdrawToken: '0x0000000000000000000000000000000000000000',
      validFrom: [BigNumber],
      validUntil: [BigNumber],
      ergsPerStorage: [BigNumber],
      ergsPerPubdata: [BigNumber],
      factoryDeps: [Array]
    },
    hash: '0x47262a7da8aefd96be4fb255dc316d62345b62219cefb38621f33c4fdd028151',
    from: '0xd535bAd504CDd77e2C51dE26F416693DF7a01ac8',
    confirmations: 0
  },
  transactionHash: '0x47262a7da8aefd96be4fb255dc316d62345b62219cefb38621f33c4fdd028151'
}
```

My hardhat config:

```
const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.4",
    settings: {
      optimizer: {
        enabled: true,
        runs: 2,
      },
    },
  },

   zksolc: {
    version: "0.1.0",
    compilerSource: "docker",
    settings: {
      optimizer: {
        enabled: true,
      },
      experimental: {
        dockerImage: "matterlabs/zksolc",
      },
    },
  },
  zkSyncDeploy: {
    zkSyncNetwork: "https://zksync2-testnet.zksync.dev",
    ethNetwork: `https://goerli.infura.io/v3/${process.env.INFURA_PROJECT_ID}`,
  },
  networks: {
    // To compile with zksolc, this must be the default network.
    hardhat: {
      zksync: true,
    },
  },
}
```

**Comment by ly0va** [comment]
Hi @joewagner thanks for reaching out! Nonces start at 0 and are incremented by 1 each time your transaction is accepted. We're investigating why you're facing this error, will get back to you once we have an answer.

**Comment by perekopskiy** [comment]
Hi @joewagner, can you check if it works now. We experienced some issues, now they should be resolved

**Comment by joewagner** [comment]
@perekopskiy @ly0va Thanks for the quick response!  Tried again just now and I'm still getting the same error.  I just joined your discord, if you prefer discussing there feel free to dm or @ me there at njwags#8346

**Comment by perekopskiy** [comment]
@joewagner please, check one more time, we've fixed another related issue

**Comment by joewagner** [comment]
@perekopskiy Looks like it's working, I'm seeing an error say I don't have "enough balance to cover the fee" but that is an issue on my end.  I believe I know how to fix that.
thanks for the help with this!
