### ISSUE TITLE
Error in plugin @matterlabs/hardhat-zksync-deploy: Deploy function does not exist or exported invalidly.

### ISSUE THREAD

**Issue by haerker** [matter-labs/hardhat-zksync#967]
### 🐛 Bug Report for hardaht-zksync plugins
Error in plugin @matterlabs/hardhat-zksync-deploy: Deploy function does not exist or exported invalidly.
#### 💥 Plugin name
@matterlabs/hardhat-zksync-deploy
Provide a plugin name where the bug appeared.

#### 📝 Description
```

#### 🔄 Reproduction Steps

1. Step 1：when i `yarn hardhat deploy-zksync`
2. Step 2
3. ...

#### 🤔 Expected Behavior

Describe what you expected to happen.

#### 😯 Current Behavior

Describe what actually happened.

#### 🖥️ Environment

- **Node version**: [e.g., Node 18.16.1]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:
- 

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output
yarn run v1.22.22
$ /home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/.bin/hardhat deploy-zksync --network local --show-stack-traces
Error in plugin @matterlabs/hardhat-zksync-deploy: Deploy function does not exist or exported invalidly.

ZkSyncDeployPluginError: Deploy function does not exist or exported invalidly.
    at ScriptManager._getDeployFunc (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/@matterlabs/hardhat-zksync-deploy/src/script-manager.ts:90:19)
    at ScriptManager.collectTags (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/@matterlabs/hardhat-zksync-deploy/src/script-manager.ts:104:41)
    at async ScriptManager.callDeployScripts (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/@matterlabs/hardhat-zksync-deploy/src/script-manager.ts:67:32)
    at async SimpleTaskDefinition.zkSyncDeploy [as action] (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/@matterlabs/hardhat-zksync-deploy/src/task-actions.ts:13:5)
    at async Environment._runTaskDefinition (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Environment.run (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at async main (/home/haerker/zksync/cross-chain-tutorial/L2-counter/node_modules/hardhat/src/internal/cli/cli.ts:323:7)
error Command failed with exit code 1.
```
Provide a clear and concise description of the bug.

```
Paste any relevant log output here.
```

**Comment by nikola-bozin-txfusion** [comment]
Hello @haerker, could you share the script you want to execute using `yarn hardhat deploy-zksync` command?
